/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodforthoughtmanagementsystem;

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 073685257
 */
public class Panel02_DefaultLeader extends javax.swing.JFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy-hh:mm");
//            jLabel1.setVisible(false);
//            jLabel2.setVisible(false);
//            dateField.setVisible(false);
//            timeInField.setVisible(false);
//            timeOutField.setVisible(false);
    /**
     * Creates new form Panel04_DefaultLeader
     */
    public Panel02_DefaultLeader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        timeInOut = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        timeInField = new javax.swing.JTextField();
        timeOutField = new javax.swing.JTextField();
        activitySelection = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("View History");

        timeInOut.setText("Sign In");
        timeInOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeInOutActionPerformed(evt);
            }
        });

        jButton3.setText("Money");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Manage");

        timeInField.setText("hh:mm");
        timeInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeInFieldActionPerformed(evt);
            }
        });

        timeOutField.setText("hh:mm");
        timeOutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeOutFieldActionPerformed(evt);
            }
        });

        activitySelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "R", "P", "L" }));
        activitySelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activitySelectionActionPerformed(evt);
            }
        });

        jLabel1.setText("Time In:");

        jLabel2.setText("Time Out:");

        dateField.setText("MM/dd/yyyy");
        dateField.setAutoscrolls(false);
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeInOut)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(activitySelection, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeInField)
                            .addComponent(timeOutField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(timeInOut)
                    .addComponent(activitySelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void timeInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeInOutActionPerformed
        // TODO add your handling code here:

//      0. Regular
//      1. Buying
//      2. Writing
        Date d = new Date();
        Date d2;
        if (timeInOut.getText().equalsIgnoreCase("Sign In") && activitySelection.getSelectedIndex() == 0) {

            d = new Date();
            //time in of the user equals this
            //TK1 save the time in
            //show the user
            timeInOut.setText("Sign Out");
            //Object[] options = {"Login"};
            //int n = JOptionPane.showOptionDialog(this, "You are signed in at " + d.toString(), "Sign In", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0],);

            Member current = new Member(Panel01_LoginScreen.loginNumber);
            current.storeTimeIn('R', d);

            JOptionPane.showMessageDialog(this, "You are signed in at " + d.toString());

        } else if (timeInOut.getText().equalsIgnoreCase("Sign Out")) {
            //time out of the user equals this
            d2 = new Date();
            Member current = new Member(Panel01_LoginScreen.loginNumber);
            current.storeTimeOut(d2);
            //TK
        } else if (activitySelection.getSelectedIndex() != 0) {
            String dayOf = dateField.getText();
            String timeIn = timeInField.getText();
            String timeOut = timeOutField.getText();
            //TK error catching
            try {
                Hours.sdfDay.parse(dayOf);
                Hours.sdfClock.parse(timeIn);
                Hours.sdfClock.parse(timeIn);
                //get date from that 
                Member current = new Member(Panel01_LoginScreen.loginNumber);
                if (activitySelection.getSelectedIndex() == 1) {
                    current.addHours(dayOf, "P", timeIn, timeOut, 0);
                } else {
                    current.addHours(dayOf, "L", timeIn, timeOut, 0);
                }
            } catch (ParseException ex) {
                Logger.getLogger(Panel02_DefaultLeader.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "You didn't use the right format for date", "Parsing Error", JOptionPane.ERROR_MESSAGE);
            }

        }


    }//GEN-LAST:event_timeInOutActionPerformed

    private void timeOutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeOutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeOutFieldActionPerformed

    private void timeInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeInFieldActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void activitySelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activitySelectionActionPerformed
        // TODO add your handling code here:
        if (activitySelection.getSelectedIndex() != 0) {
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            dateField.setVisible(true);
            timeInField.setVisible(true);
            timeOutField.setVisible(true);
        }
    }//GEN-LAST:event_activitySelectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel02_DefaultLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel02_DefaultLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel02_DefaultLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel02_DefaultLeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel02_DefaultLeader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox activitySelection;
    private javax.swing.JTextField dateField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField timeInField;
    private javax.swing.JButton timeInOut;
    private javax.swing.JTextField timeOutField;
    // End of variables declaration//GEN-END:variables
}
